apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<your-account-id>:role/GitHubActionsOIDCRole
      username: github-actions
      groups:
        - system:masters
    - rolearn: arn:aws:iam::<your-account-id>:role/node-skill
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::<your-account-id>:user/sachin-admin
      username: sachin-admin
      groups:
        - system:masters

 
