apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-api.fullname" . }}-config
data:
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  GREETING: {{ .Values.env.GREETING | quote }}
  APP_VERSION: {{ .Values.env.APP_VERSION | quote }}
