apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flask-api.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "flask-api.fullname" . }}
    spec:
      containers:
        - name: flask-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "flask-api.fullname" . }}-config
                  key: APP_ENV
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: {{ include "flask-api.fullname" . }}-config
                  key: GREETING
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "flask-api.fullname" . }}-config
                  key: APP_VERSION
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 6 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 6 }}
      affinity: {{ toYaml .Values.affinity | nindent 6 }}
